name: Test Hadrian GHC-in-GHCi

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  # pre-cleanup:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: CheckSpace
  #       shell: bash
  #       run: df -h
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Free Disk Space (Ubuntu)
  #       uses: jlumbroso/free-disk-space@main
  #       with:
  #         # this might remove tools that are actually needed,
  #         # if set to "true" but frees about 6 GB
  #         tool-cache: false
  #         # all of these default to true, but feel free to set to
  #         # "false" if necessary for your workflow
  #         android: true
  #         dotnet: true
  #         haskell: false
  #         large-packages: true
  #         docker-images: false
  #         swap-storage: true

  hadrian-build-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    # needs: [pre-cleanup]
    strategy:
      fail-fast: true
      matrix:
        # You can add multiple configurations here if needed
        config: [default]
    # container:
    #   # image: soulomoon/ghc-build-env:latest
    #   # image: registry.gitlab.haskell.org/ghc/ci-images/aarch64-linux-deb12:latest
    #   image: soulomoon/ci-images-x86_64-linux-deb12:latest
    #   options: --user root
    env:
      # GHC_FLAGS: -Werror
      # BIGNUM_BACKEND: gmp
      BIN_DIST_NAME: ghc-aarch64-linux-deb10-validate
      BUILD_FLAVOUR: validate
      # CONFIGURE_ARGS: --enable-strict-ghc-toolchain-check
      # INSTALL_CONFIGURE_ARGS: --enable-strict-ghc-toolchain-check
      TEST_ENV: aarch64-linux-deb10-validate
    defaults:
      run:
        shell: bash
    steps:
      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'cleave'
          witness-carnage: false # Default: false
      - uses: DeterminateSystems/nix-installer-action@main
      # - uses: DeterminateSystems/magic-nix-cache-action@main
      # - uses: DeterminateSystems/flake-checker-action@main
      - name: Checkout
        uses: actions/checkout@v4

      # - name: CheckSpace
      #   shell: bash
      #   run: sudo du -h --max-depth=3 /


      # - name: Maximize build space
      #   uses: ./.github/actions/free-up-space
      #   with:
      #     remove-dotnet: 'true'
      #     remove-android: 'true'
      #     remove-haskell: 'false'
      #     remove-codeql: 'true'
      #     remove-docker-images: 'false'
      #     remove-large-packages: 'true'
      #     remove-cached-tools: 'true'
      #     # remove-swapfile: 'true'
      #     verbose: 'true'

      - name: Run Hadrian build test
        shell: bash

        run: |
          git config user.email "ghc-ci@gitlab-haskell.org"
          git config user.name "GHC GitLab CI"
          # cachix useghc-nix
          nix develop git+https://gitlab.haskell.org/ghc/ghc.nix --accept-flake-config
          . .gitlab/ci.sh setup
          . .gitlab/ci.sh configure
          . .gitlab/ci.sh build_hadrian
          . .gitlab/ci.sh test_hadrian
