name: Development test

on: push

jobs:
  hadrian-build-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    # needs: [pre-cleanup]
    strategy:
      fail-fast: true
      matrix:
        # You can add multiple configurations here if needed
        config: [default]
    # container:
    #   # image: soulomoon/ghc-build-env:latest
    #   # image: registry.gitlab.haskell.org/ghc/ci-images/aarch64-linux-deb12:latest
    #   image: soulomoon/ci-images-x86_64-linux-deb12:latest
    #   options: --user root
    env:
      # GHC_FLAGS: -Werror
      # BIGNUM_BACKEND: gmp
      BIN_DIST_NAME: ghc-aarch64-linux-deb10-validate
      BUILD_FLAVOUR: validate
      # CONFIGURE_ARGS: --enable-strict-ghc-toolchain-check
      # INSTALL_CONFIGURE_ARGS: --enable-strict-ghc-toolchain-check
      TEST_ENV: aarch64-linux-deb10-validate
    defaults:
      run:
        shell: bash
    steps:
      - uses: wimpysworld/nothing-but-nix@main
        with:
          hatchet-protocol: 'cleave'
          witness-carnage: false # Default: false
          root-safe-haven: '54000'
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Checkout
        uses: actions/checkout@v4


      - name: setup git
        run: |
          git config user.email "ghc-ci@gitlab-haskell.org"
          git config user.name "GHC GitLab CI"

      - uses: nicknovitski/nix-develop@main
        with:
            arguments: "git+https://github.com/soulomoon/ghc.nix#llvm --accept-flake-config"

      - name: Hadrian setup
        run: |
          git submodule update --init
          cabal update
          cabal install happy-1.20.1.1 --overwrite-policy=always
          cabal install alex
          ./boot

      - name: Hadrian configure
        run:
          ./configure

      - name: CheckSpace
        shell: bash
        run: df -h

      - name: Hadrian build
        run:  ./hadrian/build -j10 --flavour=quickest
